In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [9]:
#1D array
arr_1d=np.array([1,2,3])
print(arr_1d)
print(arr_1d.ndim)

[1 2 3]
1


In [10]:
#2D array
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
2


In [15]:
#3D array
arr_3d=np.array([[[1,2,3],[4,5,6]],[[2,4,6],[7,8,9]]])
print(arr_3d)
print(arr_3d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[2 4 6]
  [7 8 9]]]
3


In [19]:
#array of zeros
zeros=np.zeros((2,2))
print(zeros)

[[0. 0.]
 [0. 0.]]


In [20]:
#array of ones
ones=np.ones((2,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
#array of random values
rand_arr=np.random.random((2,3))
print(rand_arr)

[[0.60235897 0.71276383 0.89211936]
 [0.61728116 0.55217667 0.47055574]]


In [22]:
#identity matrix
ident=np.eye(3)
print(ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#array with a range of values
range=np.arange(0,10,2)#start,stop,step
print(range)

[0 2 4 6 8]


In [24]:
#array attributes
arr=np.array([[1,2,3],[3,4,5]])
print("shape:",arr.shape)
print("size:",arr.size)
print("data type:",arr.dtype)
print("dimension:",arr.ndim)

shape: (2, 3)
size: 6
data type: int64
dimension: 2


In [28]:
#example
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("shape:",temp_data.shape)
print("size:",temp_data.size)
print("data type:",temp_data.dtype)
print("dimension:",temp_data.ndim)
updated_temp_data=np.array([[22,25,20],[24,26,23],[21,23,22]])
sensor_error_flags=np.zeros((2,3))
gh_identity=np.eye(3)
print("updated:",updated_temp_data)
print("sensor errors:",sensor_error_flags)
print("greenhouse:",gh_identity)

[[22 25 20]
 [24 26 23]]
shape: (2, 3)
size: 6
data type: int64
dimension: 2
updated: [[22 25 20]
 [24 26 23]
 [21 23 22]]
sensor errors: [[0. 0. 0.]
 [0. 0. 0.]]
greenhouse: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
#indexing and slicing
#indexing:same as accessing an element by index
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,2])
print(arr[1,-2])

3
5


In [30]:
#slicing:taing elements from one given index to another given index
#[start:end],[start:end:step]
print(arr[:,1:])

[[2 3]
 [5 6]]


In [42]:
#example
#row=fruits(apples,oranges),col=days(mon-sun)
shipments=np.array([[50,40],[60,45],[55,50],[70,60],[65,55],[80,70],[90,75]])
print(shipments)
print("apples shipped on wed:",shipments[2,0])
print("oranges shiped on sunday:",shipments[6,1])
#slicing
print("weekday shipments:",shipments[:5,:])
print("weekend shipments:",shipments[5:,:])
print("apples from wed to sat:",shipments[2:6,:1])
shipments[5,0]=100
print("replaced 80 apples on sat with 100:",shipments[5,0])

[[50 40]
 [60 45]
 [55 50]
 [70 60]
 [65 55]
 [80 70]
 [90 75]]
apples shipped on wed: 55
oranges shiped on sunday: 75
weekday shipments: [[50 40]
 [60 45]
 [55 50]
 [70 60]
 [65 55]]
weekend shipments: [[80 70]
 [90 75]]
apples from wed to sat: [[55]
 [70]
 [65]
 [80]]
replaced 80 apples on sat with 100: 100


In [44]:
#array operations
#a.arithmetic
a=np.array([1,2,3])
b=np.array([4,5,6])
#element wise addition 
print(a+b)
#element wise multiplication
print(a*b)
#scarlar opeartions
print(a*2)
#matrix multiplication
mat1=np.array([[1,2,],[3,4]])
mat2=np.array([[5,6],[7,8]])
res=np.dot(mat1,mat2)
print(res)

[5 7 9]
[ 4 10 18]
[2 4 6]
[[19 22]
 [43 50]]


In [48]:
#Broadcasting-numpy automatically applies operations across arrays of different shapes when compatible
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [55]:
#universal functions
"""
1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1 
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)
"""
arr=np.array([1,2,3])
arr2=np.array([4,5,6])
#exponentiation
print(np.exp(arr))
#square root
print(np.sqrt(arr))
#logarithm
print(np.log(arr))
#power
print(np.power(arr,arr2))
print(np.var(arr))
print(np.invert(arr))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[  1  32 729]
0.6666666666666666
[-2 -3 -4]


In [86]:
#example
#rows-panels,cols-hours
'''
1.Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
'''
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.stack([farmA,farmB,farmC])
print(production_all)
'''
2.Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
'''
print("shape:",production_all.shape)
print("size:",production_all.size)
print("data type:",production_all.dtype)
print("dim:",production_all.ndim)
'''
3.Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
'''
total_per_farm=production_all.sum(axis=(1,2))
print("sum of each farm:",total_per_farm)
print("mean:",production_all.mean(axis=(1,2)))
print("std:",production_all.std(axis=(1,2)))
print("var:",production_all.var(axis=(1,2)))
'''
4.Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
'''
hr_wts=np.array([0.5,1.0,0.75])
weighted_per_panel=production_all@hr_wts
print(weighted_per_panel)
'''
5.Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
'''
a=0.5
production_all=np.stack([farmA,farmB+a,farmC])
print("updated farmB:",production_all)
'''
6.Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
'''
ma=np.mean(farmA)
mb=np.mean(farmB)
mc=np.mean(farmC)
sa=np.std(farmA)
sb=np.std(farmB)
sc=np.std(farmC)
da=np.divide(farmA-ma,sa)
db=np.divide(farmB-mb,sb)
dc=np.divide(farmC-mc,sc)
normalized=np.stack([da,db,dc])
print("normalised:",normalized)

#7.apply many ufuncs
'''
8.Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
'''
panel_totals_per_farm = production_all.sum(axis=2)
print("Total energy per panel (farms × panels):")
print(panel_totals_per_farm)
print("Shape:", panel_totals_per_farm.shape)
needs_maintenance=np.any(panel_totals_per_farm<40,axis=1)
print("maintanance needed:",needs_maintenance)

'''
9.Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.
'''
overall_total=np.sum(production_all)
print("sum of all farms:",overall_total)
peak_hour=np.max(production_all)
print("peak hour:",peak_hour)
avg_per_panel=production_all.mean(axis=0)
print("avg panel across all farms:",avg_per_panel)

[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
shape: (3, 4, 3)
size: 36
data type: int64
dim: 3
sum of each farm: [126 234 174]
mean: [10.5 19.5 14.5]
std: [1.97905701 1.97905701 1.97905701]
var: [3.91666667 3.91666667 3.91666667]
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
updated farmB: [[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]
normalised: [[[-0.25264558  0.75793673  0.25264558]
  [-0.75793673  0.25264558 -0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]

 [[ 0.25264558 -0.25264558  0.75793673]
  [-0.75793673  0.25264558 -0.25264558]
  [ 1.26322788  1.76851903  0.75793673]
  [-1.26322788 -0.75793673 -

In [87]:
#Reshaping-reshaping the array size
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
#stacking and splitting
#stacking
a=np.array([1,2])
b=np.array([3,4])
#vertical stack
print("vertical:",np.vstack((a,b)))#a at 0 index and b at 1 index
#horizontal
print("horizontal:",np.hstack((a,b)))

vertical: [[1 2]
 [3 4]]
horizontal: [1 2 3 4]


In [96]:
#splitting
arr=np.array([1,2,3,4,5,6])
#split into 3 parts
print(np.array_split(arr,5))

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [98]:
#advanced indexing
#a.boolean indexing
arr=np.array([1,2,3,4,5])
print("arr>3:",arr[arr>3])
#b.fancy indexing
indices=[0,2]
print("elements at indices 0,2:",arr[indices])

arr>3: [4 5]
elements at indices 0,2: [1 3]


In [103]:
#copy vs view
#view shares memory,copy does not shares the memory(chnages wont update in the original data)
arr=np.array([1,2,3])
view=arr.view()
view[0]=17
print(arr)
copy=arr.copy()
copy[0]=21
print(arr)
print(copy)

[17  2  3]
[17  2  3]
[21  2  3]


In [104]:
#saving and loading
#save to a file
ar=np.array([1,2,3])
np.save('array.npy',ar)
#load from a file
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


In [128]:
'''
TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1
'''
arr1=np.arange(10,51)
print(arr1)
arr2=np.random.random((3,3))
print(arr2)
'''
1.Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
'''
print("shape of arr1:",arr1.shape)
print("size of arr1:",arr1.size)
print("data type of arr1:",arr1.dtype)
print("shape of arr2:",arr2.shape)
print("size of arr2:",arr2.size)
print("dtype of arr2:",arr2.dtype)
print(arr2.ndim)
'''
2.Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
'''
arr1=arr1+5
print(arr1)
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[5,6]])
print("product:",a*b)
'''
3.Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
'''
arr=np.arange(1,26)
arr=arr.reshape(5,5)
print(arr)
print("first row:",arr[:1])
print("last column:",arr[0:,4:])
print("subarray:",arr[0:3,0:2])
'''
4.Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
'''
arr=np.random.randint(10,100,size=10)
print(arr)
print("max:",np.max(arr))
print("min:",np.min(arr))
print("mean:",np.mean(arr))
print("std:",np.std(arr))
'''
6.Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
'''
arr=np.arange(1,13)
print(arr)
arr=arr.reshape(3,4)
print("reshaped arr:",arr)
'''
7.Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
'''
arr=np.ones((3,3))
print(arr)
ar=np.array([1,2,3])
print("adding [1,2,3] to each row:",arr+ar)
'''
8.Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
'''
arr=np.random.randint(1,50,size=18)
print(arr)
print("elements divided by 5 are:")
arr=arr[arr%5==0]
print(arr)
'''
9.Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
'''
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)
print(np.dot(a,b))
'''
10.Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.
'''
arr = np.arange(1, 17).reshape(4, 4)
print("4x4 Array:")
print(arr)
rows = np.arange(4)
cols = np.arange(4)
diagonal = arr[rows, cols]
print("\nDiagonal elements using fancy indexing:")
print(diagonal)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.15848187 0.01630411 0.76916896]
 [0.8093216  0.92827445 0.86905275]
 [0.39764342 0.09154275 0.51720893]]
shape of arr1: (41,)
size of arr1: 41
data type of arr1: int64
shape of arr2: (3, 3)
size of arr2: 9
dtype of arr2: float64
2
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
product: [[ 4 10]
 [15 24]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row: [[1 2 3 4 5]]
last column: [[ 5]
 [10]
 [15]
 [20]
 [25]]
subarray: [[ 1  2]
 [ 6  7]
 [11 12]]
[43 55 11 62 26 76 79 99 60 32]
max: 99
min: 11
mean: 54.3
std: 25.440322325002093
[ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped arr: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
adding [1,2,3] to each row: [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[46 